/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EBASS_AUTODEFS_H
#define S3EBASS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_BASS_NAME "s3eBass"
#define S3E_EXT_BASS_HASH 0x167b1419

#endif /* !S3EBASS_AUTODEFS_H */
